// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: zuvap/pago.proto

package pagopb

import (
	context "context"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pago struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdUsuario   int32  `protobuf:"varint,1,opt,name=idUsuario,proto3" json:"idUsuario,omitempty"`    // Id usuario zuvap
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"` // Viaje o  Envio paquete
	// Pay
	PaymentType             string  `protobuf:"bytes,3,opt,name=paymentType,proto3" json:"paymentType,omitempty"`                          // Tipo de medio de pago a utilizar. (TC / TD)
	CardNumber              string  `protobuf:"bytes,4,opt,name=cardNumber,proto3" json:"cardNumber,omitempty"`                            //Numero de tarjeta  sin espacios
	CardExpirationDateMonth int32   `protobuf:"varint,5,opt,name=cardExpirationDateMonth,proto3" json:"cardExpirationDateMonth,omitempty"` // Mes de expiración de la tarjeta a utilizar
	CardExpirationDateYear  int32   `protobuf:"varint,6,opt,name=cardExpirationDateYear,proto3" json:"cardExpirationDateYear,omitempty"`   // Año de expiración de la tarjeta a utilizar
	CardSecurityCode        int32   `protobuf:"varint,7,opt,name=cardSecurityCode,proto3" json:"cardSecurityCode,omitempty"`               // Código de seguridad de la tarjeta a utilizar
	CardHolderName          string  `protobuf:"bytes,8,opt,name=cardHolderName,proto3" json:"cardHolderName,omitempty"`                    // Nombre completo que figura en la tarjeta a utilizar
	Currency                string  `protobuf:"bytes,9,opt,name=currency,proto3" json:"currency,omitempty"`                                // sin viene vacio asumimos ARS
	Amount                  float64 `protobuf:"fixed64,10,opt,name=amount,proto3" json:"amount,omitempty"`                                 // importe
	// Output
	DatetimeProcess         *timestamp.Timestamp `protobuf:"bytes,11,opt,name=datetimeProcess,proto3" json:"datetimeProcess,omitempty"`                  // fecha hora de procesamiento
	PaymentId               string               `protobuf:"bytes,12,opt,name=paymentId,proto3" json:"paymentId,omitempty"`                              // el que nos vino en el CREATE
	InstallmentPlanDetailId int32                `protobuf:"varint,13,opt,name=installmentPlanDetailId,proto3" json:"installmentPlanDetailId,omitempty"` // Id que vino en el GET
	ErrorCode               int32                `protobuf:"varint,14,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	ErrorMessage            string               `protobuf:"bytes,15,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	PagoId                  string               `protobuf:"bytes,16,opt,name=pagoId,proto3" json:"pagoId,omitempty"`     // Indica el id con el cual se registro el pago realizado.
	PagoDate                string               `protobuf:"bytes,17,opt,name=pagoDate,proto3" json:"pagoDate,omitempty"` // Indica la fecha en la cual se registro el pago realizado.
}

func (x *Pago) Reset() {
	*x = Pago{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zuvap_pago_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pago) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pago) ProtoMessage() {}

func (x *Pago) ProtoReflect() protoreflect.Message {
	mi := &file_zuvap_pago_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pago.ProtoReflect.Descriptor instead.
func (*Pago) Descriptor() ([]byte, []int) {
	return file_zuvap_pago_proto_rawDescGZIP(), []int{0}
}

func (x *Pago) GetIdUsuario() int32 {
	if x != nil {
		return x.IdUsuario
	}
	return 0
}

func (x *Pago) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Pago) GetPaymentType() string {
	if x != nil {
		return x.PaymentType
	}
	return ""
}

func (x *Pago) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *Pago) GetCardExpirationDateMonth() int32 {
	if x != nil {
		return x.CardExpirationDateMonth
	}
	return 0
}

func (x *Pago) GetCardExpirationDateYear() int32 {
	if x != nil {
		return x.CardExpirationDateYear
	}
	return 0
}

func (x *Pago) GetCardSecurityCode() int32 {
	if x != nil {
		return x.CardSecurityCode
	}
	return 0
}

func (x *Pago) GetCardHolderName() string {
	if x != nil {
		return x.CardHolderName
	}
	return ""
}

func (x *Pago) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Pago) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Pago) GetDatetimeProcess() *timestamp.Timestamp {
	if x != nil {
		return x.DatetimeProcess
	}
	return nil
}

func (x *Pago) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *Pago) GetInstallmentPlanDetailId() int32 {
	if x != nil {
		return x.InstallmentPlanDetailId
	}
	return 0
}

func (x *Pago) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *Pago) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *Pago) GetPagoId() string {
	if x != nil {
		return x.PagoId
	}
	return ""
}

func (x *Pago) GetPagoDate() string {
	if x != nil {
		return x.PagoDate
	}
	return ""
}

type PagoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pago *Pago `protobuf:"bytes,1,opt,name=pago,proto3" json:"pago,omitempty"`
}

func (x *PagoRequest) Reset() {
	*x = PagoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zuvap_pago_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PagoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagoRequest) ProtoMessage() {}

func (x *PagoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zuvap_pago_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagoRequest.ProtoReflect.Descriptor instead.
func (*PagoRequest) Descriptor() ([]byte, []int) {
	return file_zuvap_pago_proto_rawDescGZIP(), []int{1}
}

func (x *PagoRequest) GetPago() *Pago {
	if x != nil {
		return x.Pago
	}
	return nil
}

type PagoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pago *Pago `protobuf:"bytes,1,opt,name=pago,proto3" json:"pago,omitempty"`
}

func (x *PagoResponse) Reset() {
	*x = PagoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zuvap_pago_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PagoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagoResponse) ProtoMessage() {}

func (x *PagoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zuvap_pago_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagoResponse.ProtoReflect.Descriptor instead.
func (*PagoResponse) Descriptor() ([]byte, []int) {
	return file_zuvap_pago_proto_rawDescGZIP(), []int{2}
}

func (x *PagoResponse) GetPago() *Pago {
	if x != nil {
		return x.Pago
	}
	return nil
}

var File_zuvap_pago_proto protoreflect.FileDescriptor

var file_zuvap_pago_proto_rawDesc = []byte{
	0x0a, 0x10, 0x7a, 0x75, 0x76, 0x61, 0x70, 0x2f, 0x70, 0x61, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x7a, 0x75, 0x76, 0x61, 0x70, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x96, 0x05, 0x0a, 0x04, 0x50,
	0x61, 0x67, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x64, 0x55, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x69, 0x64, 0x55, 0x73, 0x75, 0x61, 0x72, 0x69,
	0x6f, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x61, 0x72, 0x64, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x72, 0x64, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x38, 0x0a, 0x17, 0x63, 0x61, 0x72, 0x64, 0x45, 0x78, 0x70,
	0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x6e, 0x74, 0x68,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x17, 0x63, 0x61, 0x72, 0x64, 0x45, 0x78, 0x70, 0x69,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x12,
	0x36, 0x0a, 0x16, 0x63, 0x61, 0x72, 0x64, 0x45, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x44, 0x61, 0x74, 0x65, 0x59, 0x65, 0x61, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x16, 0x63, 0x61, 0x72, 0x64, 0x45, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44,
	0x61, 0x74, 0x65, 0x59, 0x65, 0x61, 0x72, 0x12, 0x2a, 0x0a, 0x10, 0x63, 0x61, 0x72, 0x64, 0x53,
	0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x10, 0x63, 0x61, 0x72, 0x64, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x63, 0x61, 0x72, 0x64, 0x48, 0x6f, 0x6c, 0x64, 0x65,
	0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x61, 0x72,
	0x64, 0x48, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x44, 0x0a, 0x0f, 0x64, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x0f, 0x64, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x50, 0x72,
	0x6f, 0x63, 0x65, 0x73, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x49, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x49, 0x64, 0x12, 0x38, 0x0a, 0x17, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x6d, 0x65,
	0x6e, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x18, 0x0d,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x17, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x6d, 0x65, 0x6e,
	0x74, 0x50, 0x6c, 0x61, 0x6e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x0f, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x70, 0x61, 0x67, 0x6f, 0x49, 0x64, 0x18, 0x10, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x70, 0x61, 0x67, 0x6f, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x6f, 0x44,
	0x61, 0x74, 0x65, 0x18, 0x11, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x67, 0x6f, 0x44,
	0x61, 0x74, 0x65, 0x22, 0x2e, 0x0a, 0x0b, 0x50, 0x61, 0x67, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1f, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x7a, 0x75, 0x76, 0x61, 0x70, 0x2e, 0x50, 0x61, 0x67, 0x6f, 0x52, 0x04, 0x70,
	0x61, 0x67, 0x6f, 0x22, 0x2f, 0x0a, 0x0c, 0x50, 0x61, 0x67, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x7a, 0x75, 0x76, 0x61, 0x70, 0x2e, 0x50, 0x61, 0x67, 0x6f, 0x52, 0x04,
	0x70, 0x61, 0x67, 0x6f, 0x32, 0x3d, 0x0a, 0x0b, 0x50, 0x61, 0x67, 0x6f, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x2e, 0x0a, 0x03, 0x50, 0x61, 0x79, 0x12, 0x12, 0x2e, 0x7a, 0x75, 0x76,
	0x61, 0x70, 0x2e, 0x50, 0x61, 0x67, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13,
	0x2e, 0x7a, 0x75, 0x76, 0x61, 0x70, 0x2e, 0x50, 0x61, 0x67, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x0e, 0x5a, 0x0c, 0x7a, 0x75, 0x76, 0x61, 0x70, 0x2f, 0x70, 0x61, 0x67,
	0x6f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_zuvap_pago_proto_rawDescOnce sync.Once
	file_zuvap_pago_proto_rawDescData = file_zuvap_pago_proto_rawDesc
)

func file_zuvap_pago_proto_rawDescGZIP() []byte {
	file_zuvap_pago_proto_rawDescOnce.Do(func() {
		file_zuvap_pago_proto_rawDescData = protoimpl.X.CompressGZIP(file_zuvap_pago_proto_rawDescData)
	})
	return file_zuvap_pago_proto_rawDescData
}

var file_zuvap_pago_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_zuvap_pago_proto_goTypes = []interface{}{
	(*Pago)(nil),                // 0: zuvap.Pago
	(*PagoRequest)(nil),         // 1: zuvap.PagoRequest
	(*PagoResponse)(nil),        // 2: zuvap.PagoResponse
	(*timestamp.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_zuvap_pago_proto_depIdxs = []int32{
	3, // 0: zuvap.Pago.datetimeProcess:type_name -> google.protobuf.Timestamp
	0, // 1: zuvap.PagoRequest.pago:type_name -> zuvap.Pago
	0, // 2: zuvap.PagoResponse.pago:type_name -> zuvap.Pago
	1, // 3: zuvap.PagoService.Pay:input_type -> zuvap.PagoRequest
	2, // 4: zuvap.PagoService.Pay:output_type -> zuvap.PagoResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_zuvap_pago_proto_init() }
func file_zuvap_pago_proto_init() {
	if File_zuvap_pago_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_zuvap_pago_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pago); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zuvap_pago_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PagoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zuvap_pago_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PagoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_zuvap_pago_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zuvap_pago_proto_goTypes,
		DependencyIndexes: file_zuvap_pago_proto_depIdxs,
		MessageInfos:      file_zuvap_pago_proto_msgTypes,
	}.Build()
	File_zuvap_pago_proto = out.File
	file_zuvap_pago_proto_rawDesc = nil
	file_zuvap_pago_proto_goTypes = nil
	file_zuvap_pago_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PagoServiceClient is the client API for PagoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PagoServiceClient interface {
	Pay(ctx context.Context, in *PagoRequest, opts ...grpc.CallOption) (*PagoResponse, error)
}

type pagoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPagoServiceClient(cc grpc.ClientConnInterface) PagoServiceClient {
	return &pagoServiceClient{cc}
}

func (c *pagoServiceClient) Pay(ctx context.Context, in *PagoRequest, opts ...grpc.CallOption) (*PagoResponse, error) {
	out := new(PagoResponse)
	err := c.cc.Invoke(ctx, "/zuvap.PagoService/Pay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PagoServiceServer is the server API for PagoService service.
type PagoServiceServer interface {
	Pay(context.Context, *PagoRequest) (*PagoResponse, error)
}

// UnimplementedPagoServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPagoServiceServer struct {
}

func (*UnimplementedPagoServiceServer) Pay(context.Context, *PagoRequest) (*PagoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Pay not implemented")
}

func RegisterPagoServiceServer(s *grpc.Server, srv PagoServiceServer) {
	s.RegisterService(&_PagoService_serviceDesc, srv)
}

func _PagoService_Pay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PagoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PagoServiceServer).Pay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zuvap.PagoService/Pay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PagoServiceServer).Pay(ctx, req.(*PagoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PagoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "zuvap.PagoService",
	HandlerType: (*PagoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Pay",
			Handler:    _PagoService_Pay_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zuvap/pago.proto",
}
